# Generated by Django 3.2.7 on 2021-10-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Type',
            fields=[
                ('type', models.CharField(max_length=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('min_amount', models.IntegerField()),
                ('max_amount', models.IntegerField()),
                ('tenor', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan_type')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('is_loan_fund', models.BooleanField()),
                ('is_taken', models.BooleanField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan_template')),
            ],
        ),
    ]
