# Generated by Django 3.2.7 on 2021-10-20 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_alter_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='type',
            field=models.ForeignKey(db_constraint=False, default='', on_delete=django.db.models.deletion.CASCADE, to='loans.loan_template'),
        ),
    ]
