# Generated by Django 3.2.7 on 2021-10-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_loan_fund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
    ]
