# Generated by Django 3.2.7 on 2021-10-22 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='pmt',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Loan_to_Loan_Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='loans.loan')),
                ('loan_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loan')),
            ],
        ),
    ]
