# Generated by Django 3.2.7 on 2021-10-23 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0010_auto_20211022_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_to_loan_fund',
            old_name='loan',
            new_name='loan_col',
        ),
        migrations.AlterField(
            model_name='ledger',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_set1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans_set2', to=settings.AUTH_USER_MODEL),
        ),
    ]
