# Generated by Django 3.2.7 on 2021-10-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0011_auto_20211023_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Installment_amount', models.FloatField()),
                ('number_pays', models.IntegerField()),
            ],
        ),
    ]
