# Generated by Django 3.2.7 on 2021-10-30 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0012_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ammortization_Table_Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Principal', models.FloatField()),
                ('Interest', models.FloatField()),
                ('Instalement', models.FloatField()),
                ('Balance', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
