# Generated by Django 3.2.7 on 2021-10-30 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0013_ammortization_table_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ammortization_table_row',
            name='user',
        ),
        migrations.CreateModel(
            name='Ammortization_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ammortization_table_row',
            name='am_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.ammortization_table'),
        ),
    ]
