# Generated by Django 3.2.7 on 2021-10-31 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_auto_20211031_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ammortization_table',
            name='user',
        ),
        migrations.RemoveField(
            model_name='ammortization_table_row',
            name='am_table',
        ),
        migrations.DeleteModel(
            name='payments',
        ),
        migrations.DeleteModel(
            name='Ammortization_Table',
        ),
        migrations.DeleteModel(
            name='Ammortization_Table_Row',
        ),
    ]
